# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: "api"
source:
    root: /projects/api/display-api-service

# The runtime the application uses.
type: "php:8.0"

runtime:
  extensions:
    - redis
    - apcu
    - ctype
    - iconv
    - mbstring
    - sodium
    - xsl

# Configuration of the build of this application.
build:
  flavor: none

variables:
  php:
    opcache.preload: /app/config/preload.php
    memory_limit: 256M
    env:
        # Tell Symfony to always install in production-mode.
        APP_ENV: 'prod'
        APP_DEBUG: 0
        # TODO: Find a way to avoid this
        CORS_ALLOW_ORIGIN: "*"

# The build-time dependencies of the app.
dependencies:
  php:
    composer/composer: "^2"

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  database: "mysqldb:mysql"
  redis: "rediscache:redis"

# The configuration of app when it is exposed to the web.
web:
  # Specific parameters for different URL prefixes.
  locations:
    "/":
      root: "public"
      expires: 1h
      passthru: "/index.php"
disk: 1024

mounts:
  "/var": { source: local, source_path: var }


# The hooks executed at various points in the lifecycle of the application.
hooks:
  build: |
    set -x -e
    curl -fs https://get.symfony.com/cloud/configurator | bash
    symfony-build
    # platform variable:create --level environment --name APP_ENV --value prod  --visible-build false --visible-runtime true
    # platform variable:create --level environment --name APP_SECRET --value prod  --visible-build false --visible-runtime true
    # platform variable:create --level environment --name APP_ENV --value prod  --visible-build false --visible-runtime true
    # export APP_ENV=prod
    # export APP_SECRET=quite_unsafe
    # # TODO, don't do this
    # export CORS_ALLOW_ORIGIN=*
    # envsubst '$APP_ENV $APP_SECRET $CORS_ALLOW_ORIGIN' < template-config.json > config/config.json

  # We run deploy hook after your application has been deployed and started.
  deploy: |
    set -x -e
    symfony-deploy

# The configuration of scheduled execution.
crons:
  backup:
    spec: '15 0 * * *'
    cmd: |
        if [ "$PLATFORM_ENVIRONMENT_TYPE" = production ]; then
            platform backup:create --yes --no-wait
        fi
