# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: "api"
source:
    root: /projects/api/display-api-service

# The runtime the application uses.
type: "php:8.0"

runtime:
  extensions:
    - redis
    - apcu
    - ctype
    - iconv
    - mbstring
    - sodium
    - xsl

# Configuration of the build of this application.
build:
  flavor: none

variables:
  php:
    opcache.preload: /app/config/preload.php
    memory_limit: 256M
  env:
      # Tell Symfony to always install in production-mode.
      APP_ENV: 'prod'
      APP_DEBUG: 0
      JWT_SECRET_KEY: "%kernel.project_dir%/var/jwt/private.pem"
      JWT_PUBLIC_KEY: "%kernel.project_dir%/var/jwt/public.pem"
      # TODO: Find a way to avoid this
      CORS_ALLOW_ORIGIN: "*"

# The build-time dependencies of the app.
dependencies:
  php:
    composer/composer: "^2"

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  database: "mysqldb:mysql"
  redis: "rediscache:redis"
  # The following is added for us to get a shortcort for getting a domain
  admin: "admin:http"
  display: "display:http"


# The configuration of app when it is exposed to the web.
web:
  # Specific parameters for different URL prefixes.
  locations:
    "/":
      root: "public"
      expires: 1h
      passthru: "/index.php"
disk: 1024

mounts:
  "/var": { source: local, source_path: var }


# The hooks executed at various points in the lifecycle of the application.
hooks:
  build: |
    set -x  -e
    curl -fs https://get.symfony.com/cloud/configurator | bash
    symfony-build

    export
    ln -s /var/.env.local .env.local

  # We run deploy hook after your application has been deployed and started.
  deploy: |
    set -x -e
    symfony-deploy
    test -f /var/jwt/private.pem || bin/console lexik:jwt:generate-keypair
    touch /var/.env.local
    export

# The configuration of scheduled execution.
crons:
  backup:
    spec: '15 0 * * *'
    cmd: |
        if [ "$PLATFORM_ENVIRONMENT_TYPE" = production ]; then
            platform backup:create --yes --no-wait
        fi
