name: admin

# Static web-app, we want to allocate as few resources as possible.
size: S

type: nodejs:14

build:
  # We set flavor to none in order to use yarn.
  # https://docs.platform.sh/languages/nodejs.html#use-yarn-as-a-package-manager
  flavor: none

dependencies:
  nodejs:
    # Latest yarn.
    yarn: "*"

# The configuration of app when it is exposed to the web.
web:
  locations:
      "/admin":
          root: "display-admin-client/build"
          # Default to serve our static index
          index: ['index.html']
          # No not allow any scripts
          scripts: false
          # Any misses should go to index.html which will result in React
          # handling the request
          passthru: "/admin/index.html"
          rules:
            '^/admin/config.json$':
              # Enable caching
              # This will take the load off the server and generally prevent the
              # client request to reach the backend server.
              expires: 10m

# Build the react app and copy/render any templates that will be needed by
# the app at runtime.
hooks:
  build: |
    set -e
    cd display-admin-client
    yarn install
    PUBLIC_URL=/admin yarn build
    cp ../config-template/template-config.json build/config.json
    cp ../config-template/template-access-config.json build/access-config.json

